#!/usr/bin/env ruby
# Confmacs - Switch between Emacs configurations with ease.
# Copyright (C) 2015 Severen Redwood <severen.redwood@gmail.com>
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# The gems 'thor', 'colorize' and 'highline' are required to run this script.
# You can install the dependencies via this command:
# `gem install thor colorize highline`

require 'thor'
require 'colorize'
require 'highline/import'
require 'fileutils'

HOME = Dir.home
CONFIG_DIR = "#{HOME}/.confmacs"
EMACS_CONFIG_DIR = "#{CONFIG_DIR}/configs"

def config_dir_check
  if !File.exist?(CONFIG_DIR)
    FileUtils.mkdir(CONFIG_DIR)
    FileUtils.mkdir("#{CONFIG_DIR}/configs")
  elsif !File.exist?("#{CONFIG_DIR}/configs")
    FileUtils.mkdir("#{CONFIG_DIR}/configs")
  end
end

def config_scan
  config_dir_check
  configs = Dir.entries("#{CONFIG_DIR}/configs")
  configs -= %w(. ..)
  configs.map(&:to_sym)
end

class CLI < Thor
  map %w(version -V --version) => :__print_version

  desc 'init', 'Create the  ~/.confmacs directory'
  long_desc <<-LONGDESC
    `confmacs init` will create a new ~/.confmacs directory if it does not
    exist.
  LONGDESC
  def init
    config_dir_check
  end

  desc 'list', 'List the Emacs configs stored under ~/.confmacs/configs/'
  long_desc <<-LONGDESC
    `confmacs list` will print a list of all the available Emacs configurations
    that are stored under the ~/.confmacs/configs/ directory.

    These different configurations can be selected with the `confmacs select`
    command.
  LONGDESC
  def list
    puts '==> Available Emacs configurations:'.colorize(:green)
    puts config_scan
  end

  desc 'select <config>', 'Select the active Emacs config'
  long_desc <<-LONGDESC
    `confmacs select` will change the ~/.emacs.d symlink to point towards the
    selected configuration.

    You can view a list of the available configurations (stored in
    ~/.confmacs/configs/) with the `confmacs list` command.
  LONGDESC
  def select(config)
    config_dir_check
    config_path = "#{EMACS_CONFIG_DIR}/#{config}"
    unless File.exist?("#{config_path}")
      Kernel.abort("The configuration '#{config}' does not exist!"
      .colorize(:red))
    end

    puts '~/.emacs.d will be deleted and replaced with a symlink.'
      .colorize(:red).blink
    exit unless HighLine.agree('Do you want to proceed? (Y/N)')
    FileUtils.remove("#{HOME}/.emacs.d")
    FileUtils.symlink("#{config_path}", "#{HOME}/.emacs.d")
  end

  desc 'version', 'Print version info and exit'
  def __print_version
    puts "Confmacs 0.1.0\n".colorize(:blue)

    puts 'Copyright (C) 2015 Severen Redwood <severen.redwood@gmail.com>'
      .colorize(:red)
    puts 'This is free software; see the source for copying conditions.'
      .colorize(:red)
  end
end

CLI.start(ARGV)
